services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "9000:80"

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=direct_operator
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
