version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=direct_operator
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # ports:
    #  - 3307:3306

  web:
    build: .
    volumes:
      - ./:/var/www/html 
    ports:
      - '8080:80'
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1